### ISSUE TITLE
Use pull requests for the win!

### ISSUE THREAD

**Issue by mattmenefee** [tkbpule1/timblr#1]
Looks good so far! You should open up pull requests for each chunk of work / feature that you build from here on out. Also, check out this post about [commit messages](http://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html).

**Comment by tkbpule1** [comment]
hey if you have time checkout the Picture Uploader. i cant get it to work,
in development nor in production-via heroku. not sure why. i followed
hartl's tutorial to the T.

**Comment by mattmenefee** [comment]
do you have a branch with those changes on it somewhere?

**Comment by tkbpule1** [comment]
so if you go to my commits, scroll to microposts, these are the files that
i changed specifically for the picture.

I'll tell you exactly what i did:

I added these gems to the _gemfile_:

_gem 'carrierwave',    '0.10.0'_
_gem 'mini_magick',  '3.8.0'_
_gem 'fog',                '1.36.0'_

then, I installed them with: bundle install

next, i generated the uploader:

_$  rails g uploader Picture_

after that, i generated the migration and migrated the development database:

_$  rails g migration add_picture_to_microposts picture:string_
_$  bundle exec rake db:migrate_

next, in _app/models/micropost.rb_  I told CarrierWave to associate the
image with my model:
added:

_mount_uploader :picture, PictureUploader_

next, in _app/views/shared/_micropost_form.html.erb_:
i updated the form to have multiple parts:

_<%= form_for (@micropost, html: { multipart: true }) do | f | %>_

_<span class="picture">_
-  <%= f.file_field :picture %>*
  _</span>_

after that, i included the symbol :picture in
_app/controllers/microposts_controller.rb_

_private_
- def micropost_params*
-   params.require(:micropost).permit(:comtent, :picture)*
- end*

Finally, render the image:  _app/views/microposts/_micropost.html.erb_
added:

<%= image_tag micropost.picture.url if micropost.picture? %>

Thats what i did to make it work in my development env.  I'm not sure what
i did wrong bc i'm pretty sure i followed the code exactly, bc i checked
like 10 times. but another pair of eyes is always good.

Thanks for your help
